import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  console.log({ session });

  if (status === 'loading') {
    return <main>Loading...</main>;
  }

  return (
    <>
      <Head>
        <title>Guestbook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Guestbook</h1>
        {!session && (
          <div>
            <button onClick={() => signIn('discord')}>
              Login with Discord
            </button>
          </div>
        )}
        {session && (
          <div>
            <p>Hello, {session.user?.name}</p>
            <button onClick={() => signOut()}>Sign Out</button>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
