import { Button } from '@chakra-ui/react';
import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Header from '../components/Header';
import MessagesList from '../components/MessagesList';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  console.log({ session });

  if (status === 'loading') {
    return <main>Loading...</main>;
  }

  return (
    <>
      <Head>
        <title>Guestbook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {session && (
          <div>
            <MessagesList />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
